import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'de' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Get saved language from localStorage or detect browser language
    const savedLanguage = localStorage.getItem('sport-academy-language') as Language;
    if (savedLanguage && ['en', 'de', 'it'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    } else {
      // Detect browser language
      const browserLang = navigator.language.toLowerCase();
      if (browserLang.startsWith('de')) {
        setLanguage('de');
      } else if (browserLang.startsWith('it')) {
        setLanguage('it');
      } else {
        setLanguage('en');
      }
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('sport-academy-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.classes': 'Classes',
    'nav.schedule': 'Schedule',
    'nav.coaches': 'Coaches',
    'nav.membership': 'Membership',
    'nav.contact': 'Contact',

    // Common
    'common.joinNow': 'JOIN NOW',
    'common.viewClasses': 'VIEW CLASSES',
    'common.learnMore': 'Learn More',
    'common.backToClasses': 'BACK TO CLASSES',
    'common.contactUs': 'CONTACT US',
    'common.callNow': 'CALL NOW',
    'common.viewSchedule': 'VIEW SCHEDULE',
    'common.viewMembership': 'VIEW MEMBERSHIP',
    'common.joinSportAcademy': 'JOIN SPORT ACADEMY',
    'common.allLevels': 'All Levels',
    'common.ages': 'Ages',
    'common.registerOnline': 'REGISTER ONLINE',
    'common.bookClasses': 'Book Classes',
    'common.visitUs': 'Visit Us',
    'common.dropInWelcome': 'Drop-in Welcome',
    'common.duringTrainingHours': 'During training hours',
    'common.instantConfirmation': 'Instant confirmation',
    'common.responseWithin2Hours': 'Response within 2 hours',
    'common.dailyUpdatesAndDMs': 'Daily updates & DMs',

    // Home Page
    'home.hero.title': 'SPORT ACADEMY',
    'home.hero.subtitle': 'Forging fighters since 2017',
    'home.welcome.title': 'WELCOME TO SPORT ACADEMY',
    'home.welcome.description': 'Since 2017, Sport Academy has been the premier destination for martial arts training in South Tyrol. We offer world-class instruction in MMA, Brazilian Jiu-Jitsu, and Grappling across our two state-of-the-art facilities.',
    'home.stats.yearsOfExcellence': 'Years of Excellence',
    'home.stats.yearsDescription': 'Established in 2017, we\'ve been developing fighters for over 8 years',
    'home.stats.trainingLocations': 'Training Locations',
    'home.stats.locationsDescription': 'Convenient facilities in Campo Tures and Brunico',
    'home.stats.trainingPrograms': 'Training Programs',
    'home.stats.programsDescription': 'Comprehensive classes for adults and kids of all skill levels',
    'home.stats.exploreClasses': 'EXPLORE OUR CLASSES',
    'home.trainLikeFighter.title': 'TRAIN LIKE A FIGHTER',
    'home.trainLikeFighter.subtitle': 'Master the arts of combat with professional instruction',
    'home.mma.description': 'Complete mixed martial arts training combining striking, grappling, and ground fighting techniques.',
    'home.bjj.description': 'Master the gentle art of Brazilian Jiu-Jitsu with comprehensive ground fighting techniques.',
    'home.grappling.description': 'Develop wrestling and submission skills through intensive no-gi grappling training.',
    'home.getStarted.title': 'GET STARTED TODAY',
    'home.getStarted.subtitle': 'Everything you need to begin your martial arts journey',
    'home.quickLinks.viewClasses': 'View Classes',
    'home.quickLinks.viewClassesDesc': 'Explore our training programs',
    'home.quickLinks.checkSchedule': 'Check Schedule',
    'home.quickLinks.checkScheduleDesc': 'Find the perfect class time',
    'home.quickLinks.membershipPlans': 'Membership Plans',
    'home.quickLinks.membershipPlansDesc': 'Choose your training package',
    'home.quickLinks.contactUs': 'Contact Us',
    'home.quickLinks.contactUsDesc': 'Get in touch with our team',

    // Classes Page
    'classes.hero.title': 'OUR CLASSES',
    'classes.hero.description': 'Professional training programs designed for all skill levels. From beginners taking their first steps to advanced athletes preparing for competition, we have the perfect class for your martial arts journey.',
    'classes.mma.title': 'MMA Classes',
    'classes.mma.description': 'Complete mixed martial arts training combining striking, grappling, and ground fighting techniques. Perfect for those looking to develop well-rounded combat skills.',
    'classes.mma.features': ['Striking techniques', 'Grappling fundamentals', 'Ground fighting', 'Conditioning', 'Sparring sessions'],
    'classes.bjj.title': 'Brazilian Jiu-Jitsu',
    'classes.bjj.description': 'Master the gentle art of BJJ with our comprehensive ground fighting program. Learn leverage, technique, and strategy over brute strength.',
    'classes.bjj.features': ['Guard techniques', 'Submissions', 'Escapes', 'Positional control', 'Competition preparation'],
    'classes.grappling.title': 'Grappling',
    'classes.grappling.description': 'Develop your wrestling and submission skills in our intensive grappling sessions. Focus on takedowns, control, and submissions.',
    'classes.grappling.features': ['Takedown techniques', 'Wrestling fundamentals', 'Submission grappling', 'No-gi training', 'Competition prep'],
    'classes.kidsBjj.title': 'BJJ for Kids',
    'classes.kidsBjj.description': 'Safe and fun Brazilian Jiu-Jitsu classes designed specifically for young athletes. Building confidence, discipline, and respect.',
    'classes.kidsBjj.features': ['Age-appropriate techniques', 'Character development', 'Anti-bullying skills', 'Physical fitness', 'Fun games and drills'],
    'classes.kidsGrappling.title': 'Grappling for Kids',
    'classes.kidsGrappling.description': 'Build confidence, discipline, and physical fitness through youth grappling programs. Emphasis on safety and skill development.',
    'classes.kidsGrappling.features': ['Basic wrestling moves', 'Coordination drills', 'Strength building', 'Teamwork skills', 'Safe training environment'],
    'classes.wrestling.title': 'Wrestling',
    'classes.wrestling.description': 'Traditional wrestling techniques and conditioning for competitive athletes. Build strength, endurance, and technical proficiency.',
    'classes.wrestling.features': ['Olympic wrestling', 'Freestyle techniques', 'Greco-Roman style', 'Conditioning programs', 'Competition training'],
    'classes.whatYouLearn': 'What You\'ll Learn:',
    'classes.cta.title': 'READY TO START TRAINING?',
    'classes.cta.description': 'Join Sport Academy today and begin your martial arts journey with expert instruction and a supportive community.',

    // Schedule Page
    'schedule.hero.title': 'WEEKLY SCHEDULE',
    'schedule.hero.description': 'Current Training Schedule - Find the perfect class time that fits your lifestyle. All classes are designed to accommodate different skill levels and age groups.',
    'schedule.campoTures': 'Campo Tures Location',
    'schedule.brunico': 'Brunico Location',
    'schedule.tuesday': 'Tuesday',
    'schedule.thursday': 'Thursday',
    'schedule.monday': 'Monday',
    'schedule.wednesday': 'Wednesday',
    'schedule.friday': 'Friday',
    'schedule.grappling': 'Grappling',
    'schedule.mma': 'MMA',
    'schedule.bjj': 'BJJ',
    'schedule.wrestling': 'Wrestling',
    'schedule.striking': 'Striking',
    'schedule.openMat': 'Open Mat',
    'schedule.importantInfo': 'Important Information',
    'schedule.classGuidelines': 'Class Guidelines',
    'schedule.membershipBenefits': 'Membership Benefits',
    'schedule.guidelines.arrive': 'Arrive 10 minutes early for warm-up',
    'schedule.guidelines.water': 'Bring water bottle and towel',
    'schedule.guidelines.gi': 'Gi required for BJJ classes',
    'schedule.guidelines.noGi': 'No-gi attire for MMA, Grappling, and Striking',
    'schedule.benefits.allClasses': 'Access to all scheduled classes',
    'schedule.benefits.openMat': 'Open mat sessions included',
    'schedule.benefits.bothLocations': 'Both locations available',
    'schedule.benefits.personalTraining': 'Personal training available',
    'schedule.cta.title': 'RESERVE YOUR SPOT',
    'schedule.cta.description': 'Classes fill up quickly. Secure your membership today and start training with the best in South Tyrol.',

    // Coaches Page
    'coaches.hero.title': 'OUR COACHES',
    'coaches.hero.description': 'Learn from experienced professionals who are passionate about martial arts and dedicated to helping you achieve your goals. Our coaching team brings years of competitive experience and proven teaching methods.',
    'coaches.matteo.name': 'Matteo Parolin',
    'coaches.matteo.title': 'Head Coach & Founder',
    'coaches.matteo.background': 'Matteo founded Sport Academy in 2017 with a vision to bring world-class martial arts training to South Tyrol. With over 15 years of experience in MMA and Brazilian Jiu-Jitsu, he has competed at national and international levels.',
    'coaches.matteo.specializations': ['Mixed Martial Arts (MMA)', 'Brazilian Jiu-Jitsu (Brown Belt)', 'Competition Preparation', 'Youth Development Programs'],
    'coaches.matteo.achievements': ['Regional MMA Champion (2019)', 'BJJ European Championship Medalist', 'Certified Youth Martial Arts Instructor'],
    'coaches.christian.name': 'Christian Zecchetto',
    'coaches.christian.title': 'Grappling & Wrestling Coach',
    'coaches.christian.background': 'Christian brings a wealth of wrestling and grappling expertise to Sport Academy. His technical approach and attention to detail have helped countless students improve their ground game and competitive performance.',
    'coaches.christian.specializations': ['Wrestling (Freestyle & Greco-Roman)', 'Submission Grappling', 'Takedown Techniques', 'Strength & Conditioning'],
    'coaches.christian.achievements': ['National Wrestling Championship Finalist', 'ADCC European Trials Competitor', 'Certified Wrestling Coach (Level 2)'],
    'coaches.background': 'Background',
    'coaches.specializations': 'Specializations',
    'coaches.achievements': 'Achievements',
    'coaches.philosophy.title': 'OUR COACHING PHILOSOPHY',
    'coaches.philosophy.technical.title': 'Technical Excellence',
    'coaches.philosophy.technical.description': 'We focus on proper technique and fundamentals, ensuring every student builds a solid foundation for long-term success.',
    'coaches.philosophy.individual.title': 'Individual Growth',
    'coaches.philosophy.individual.description': 'Every student is unique. We tailor our instruction to meet individual goals, whether recreational or competitive.',
    'coaches.philosophy.respect.title': 'Respect & Discipline',
    'coaches.philosophy.respect.description': 'Martial arts teaches more than fighting techniques. We emphasize respect, discipline, and character development.',
    'coaches.cta.title': 'TRAIN WITH THE BEST',
    'coaches.cta.description': 'Experience world-class instruction and personalized attention. Start your journey with Sport Academy\'s expert coaching team.',

    // Membership Page
    'membership.hero.title': 'MEMBERSHIP PLANS',
    'membership.hero.description': 'Choose the membership plan that fits your training goals and schedule. All memberships include access to both locations and all scheduled classes. No hidden fees, no long-term contracts.',
    'membership.mainSeason.title': 'Main Season',
    'membership.mainSeason.period': 'September - June',
    'membership.mainSeason.duration': '10 months of intensive training',
    'membership.mainSeason.mostPopular': 'MOST POPULAR',
    'membership.summerSeason.title': 'Summer Season',
    'membership.summerSeason.period': 'June - September',
    'membership.summerSeason.duration': '3 months of summer training',
    'membership.bjjOnly.title': 'JIU JITSU ONLY MEMBERSHIP',
    'membership.bjjOnly.subtitle': 'Dedicated Brazilian Jiu-Jitsu training for summer season',
    'membership.bjjOnly.program': 'BJJ Summer Program',
    'membership.bjjOnly.description': '3 months of focused BJJ training',
    'membership.adults': 'Adults',
    'membership.students': 'Students',
    'membership.month': 'month',
    'membership.whatsIncluded': 'What\'s Included:',
    'membership.mainIncludes': ['Unlimited access to all classes', 'Both Campo Tures & Brunico locations', 'Open mat sessions', 'Competition preparation', 'Personal training discounts'],
    'membership.summerIncludes': ['Access to summer schedule classes', 'Both locations available', 'Open training sessions', 'Flexible summer schedule', 'Outdoor training opportunities'],
    'membership.bjjIncludes': ['Access to all BJJ classes only', 'Both Campo Tures & Brunico locations', 'Gi and No-Gi training', 'Technique refinement focus', 'BJJ-specific open mat sessions'],
    'membership.selectMainSeason': 'SELECT MAIN SEASON',
    'membership.selectSummerSeason': 'SELECT SUMMER SEASON',
    'membership.selectBjjOnly': 'SELECT BJJ ONLY',
    'membership.additionalServices.title': 'ADDITIONAL SERVICES',
    'membership.additionalServices.description': 'Enhance your training with our specialized services and programs',
    'membership.personalTraining.title': 'Personal Training',
    'membership.personalTraining.description': 'One-on-one coaching sessions tailored to your specific goals',
    'membership.personalTraining.price': '€50/session',
    'membership.personalTraining.duration': '60 minutes',
    'membership.competitionPrep.title': 'Competition Prep',
    'membership.competitionPrep.description': 'Specialized training for upcoming tournaments and competitions',
    'membership.competitionPrep.price': '€80/session',
    'membership.competitionPrep.duration': '90 minutes',
    'membership.seminars.title': 'Seminars & Workshops',
    'membership.seminars.description': 'Special events with guest instructors and advanced techniques',
    'membership.seminars.price': '€30/event',
    'membership.seminars.duration': '3-4 hours',
    'membership.faq.title': 'FREQUENTLY ASKED QUESTIONS',
    'membership.faq.seasons.question': 'What\'s the difference between seasons?',
    'membership.faq.seasons.answer': 'The Main Season (September-June) offers our full program with regular classes and competition preparation. The Summer Season (June-September) has a more relaxed schedule perfect for maintaining fitness during vacation months.',
    'membership.faq.locations.question': 'Can I train at both locations?',
    'membership.faq.locations.answer': 'Yes! All memberships include access to both our Campo Tures and Brunico facilities. You can attend classes at either location based on your schedule.',
    'membership.faq.trial.question': 'Do you offer trial classes?',
    'membership.faq.trial.answer': 'Absolutely! We offer a free trial class for new students. Contact us to schedule your trial and experience our training firsthand.',
    'membership.faq.equipment.question': 'What equipment do I need?',
    'membership.faq.equipment.answer': 'For BJJ classes, you\'ll need a gi (uniform). For MMA and grappling, comfortable athletic wear is sufficient. We recommend bringing a water bottle and towel to all classes.',
    'membership.cta.title': 'START YOUR JOURNEY TODAY',
    'membership.cta.description': 'Join Sport Academy and become part of South Tyrol\'s premier martial arts community. Your transformation starts here.',

    // Contact Page
    'contact.hero.title': 'CONTACT & VISIT',
    'contact.hero.description': 'Get in touch with Sport Academy and visit our world-class training facilities. We\'re here to help you start your martial arts journey with expert guidance and support.',
    'contact.getInTouch.title': 'GET IN TOUCH',
    'contact.getInTouch.subtitle': 'Multiple ways to connect with our team',
    'contact.callUs': 'Call Us',
    'contact.instagram': 'Instagram',
    'contact.locations.title': 'OUR LOCATIONS',
    'contact.locations.subtitle': 'Two convenient facilities in South Tyrol',
    'contact.campoTures': 'Campo Tures',
    'contact.brunico': 'Brunico',
    'contact.address': 'Address',
    'contact.trainingSchedule': 'Training Schedule',
    'contact.landmarkDirections': 'Landmark Directions',
    'contact.availableClasses': 'Available Classes',
    'contact.campoTures.address': 'Via Hugo von Taufers 8\nCampo Tures, South Tyrol\nItaly',
    'contact.brunico.address': 'Via Teresa Riedl 3\n39031 Brunico BZ\nSouth Tyrol, Italy',
    'contact.campoTures.directions': 'Located in the town center, 50m from the main church. Look for the Sport Academy sign next to the pharmacy.',
    'contact.brunico.directions': '5-minute walk from Brunico train station. Near the sports complex, opposite the public swimming pool.',
    'contact.campoTures.classes': ['MMA Classes', 'Brazilian Jiu-Jitsu', 'Grappling', 'Kids BJJ'],
    'contact.brunico.classes': ['Brazilian Jiu-Jitsu', 'Wrestling', 'Kids Grappling', 'Open Training'],
    'contact.parking.title': 'PARKING & ACCESSIBILITY',
    'contact.parking.subtitle': 'Easy access and convenient parking at both locations',
    'contact.parking': 'Parking',
    'contact.publicTransport': 'Public Transport',
    'contact.accessibility': 'Accessibility',
    'contact.campoTures.parking': 'Free street parking available on Via Hugo von Taufers and surrounding streets. Public parking lot 100m away (€1/hour during business hours, free evenings).',
    'contact.campoTures.transport': 'Regular bus service from Brunico (Line 441). Bus stop "Campo Tures Centro" is 2 minutes walk from the gym.',
    'contact.campoTures.accessibility': 'Ground floor access with wide entrance. Accessible restroom facilities available.',
    'contact.brunico.parking': 'Free parking available on Via Teresa Riedl. Large public parking area near the sports complex (free after 18:00 and weekends).',
    'contact.brunico.transport': '5 minutes walk from Brunico train station. Excellent connections to Bolzano, Innsbruck, and major cities. Bus lines 441, 442, and 445.',
    'contact.brunico.accessibility': 'Wheelchair accessible entrance and facilities. Elevator access to all floors.',
    'contact.visitRequirements.title': 'VISIT REQUIREMENTS',
    'contact.visitRequirements.subtitle': 'What to know before your first visit',
    'contact.firstTimeVisitors': 'First-Time Visitors',
    'contact.whatToBring': 'What to Bring',
    'contact.whatWeProvide': 'What We Provide',
    'contact.specialInstructions': 'Special Instructions',
    'contact.bring': ['Valid ID for registration', 'Comfortable athletic wear', 'Water bottle and towel', 'Positive attitude and open mind'],
    'contact.provide': ['Free trial class (first visit)', 'Basic gloves & shin guards for MMA classes (temporary)', 'Facility tour and orientation', 'Personal consultation with coaches'],
    'contact.instructions.age': 'Age Requirements: 16+ for adult classes, 6-15 for kids programs',
    'contact.instructions.health': 'Health: Please inform us of any injuries or medical conditions',
    'contact.instructions.equipment': 'Equipment: Basic gloves & shin guards provided temporarily - students should purchase their own',
    'contact.instructions.payment': 'Payment: Cash and card accepted',
    'contact.cta.title': 'READY TO BEGIN?',
    'contact.cta.description': 'Take the first step towards your martial arts journey. Contact us today and discover your potential.',

    // Footer
    'footer.tagline': 'Elite MMA, BJJ & Grappling Training in South Tyrol',
    'footer.subtitle': 'Forging fighters since 2017',
    'footer.copyright': '© 2025 Sport Academy. All rights reserved.',
  },

  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.classes': 'Kurse',
    'nav.schedule': 'Stundenplan',
    'nav.coaches': 'Trainer',
    'nav.membership': 'Mitgliedschaft',
    'nav.contact': 'Kontakt',

    // Common
    'common.joinNow': 'JETZT BEITRETEN',
    'common.viewClasses': 'KURSE ANSEHEN',
    'common.learnMore': 'Mehr erfahren',
    'common.backToClasses': 'ZURÜCK ZU KURSEN',
    'common.contactUs': 'KONTAKT',
    'common.callNow': 'JETZT ANRUFEN',
    'common.viewSchedule': 'STUNDENPLAN ANSEHEN',
    'common.viewMembership': 'MITGLIEDSCHAFT ANSEHEN',
    'common.joinSportAcademy': 'SPORT ACADEMY BEITRETEN',
    'common.allLevels': 'Alle Stufen',
    'common.ages': 'Alter',
    'common.registerOnline': 'ONLINE ANMELDEN',
    'common.bookClasses': 'Kurse buchen',
    'common.visitUs': 'Besuchen Sie uns',
    'common.dropInWelcome': 'Spontanbesuche willkommen',
    'common.duringTrainingHours': 'Während der Trainingszeiten',
    'common.instantConfirmation': 'Sofortige Bestätigung',
    'common.responseWithin2Hours': 'Antwort innerhalb von 2 Stunden',
    'common.dailyUpdatesAndDMs': 'Tägliche Updates & DMs',

    // Home Page
    'home.hero.title': 'SPORT ACADEMY',
    'home.hero.subtitle': 'Kämpfer schmieden seit 2017',
    'home.welcome.title': 'WILLKOMMEN BEI SPORT ACADEMY',
    'home.welcome.description': 'Seit 2017 ist die Sport Academy das führende Ziel für Kampfsporttraining in Südtirol. Wir bieten erstklassigen Unterricht in MMA, Brazilian Jiu-Jitsu und Grappling in unseren beiden hochmodernen Einrichtungen.',
    'home.stats.yearsOfExcellence': 'Jahre der Exzellenz',
    'home.stats.yearsDescription': 'Gegründet 2017, entwickeln wir seit über 8 Jahren Kämpfer',
    'home.stats.trainingLocations': 'Trainingsstandorte',
    'home.stats.locationsDescription': 'Praktische Einrichtungen in Sand in Taufers und Bruneck',
    'home.stats.trainingPrograms': 'Trainingsprogramme',
    'home.stats.programsDescription': 'Umfassende Kurse für Erwachsene und Kinder aller Leistungsstufen',
    'home.stats.exploreClasses': 'UNSERE KURSE ENTDECKEN',
    'home.trainLikeFighter.title': 'TRAINIERE WIE EIN KÄMPFER',
    'home.trainLikeFighter.subtitle': 'Meistere die Kampfkünste mit professionellem Unterricht',
    'home.mma.description': 'Komplettes Mixed Martial Arts Training mit Schlag-, Grappling- und Bodenkampftechniken.',
    'home.bjj.description': 'Meistere die sanfte Kunst des Brazilian Jiu-Jitsu mit umfassenden Bodenkampftechniken.',
    'home.grappling.description': 'Entwickle Wrestling- und Submission-Fähigkeiten durch intensives No-Gi Grappling-Training.',
    'home.getStarted.title': 'HEUTE BEGINNEN',
    'home.getStarted.subtitle': 'Alles was du brauchst, um deine Kampfsportreise zu beginnen',
    'home.quickLinks.viewClasses': 'Kurse ansehen',
    'home.quickLinks.viewClassesDesc': 'Entdecke unsere Trainingsprogramme',
    'home.quickLinks.checkSchedule': 'Stundenplan prüfen',
    'home.quickLinks.checkScheduleDesc': 'Finde die perfekte Kurszeit',
    'home.quickLinks.membershipPlans': 'Mitgliedschaftspläne',
    'home.quickLinks.membershipPlansDesc': 'Wähle dein Trainingspaket',
    'home.quickLinks.contactUs': 'Kontakt',
    'home.quickLinks.contactUsDesc': 'Nimm Kontakt mit unserem Team auf',

    // Classes Page
    'classes.hero.title': 'UNSERE KURSE',
    'classes.hero.description': 'Professionelle Trainingsprogramme für alle Leistungsstufen. Von Anfängern, die ihre ersten Schritte machen, bis zu fortgeschrittenen Athleten, die sich auf Wettkämpfe vorbereiten - wir haben den perfekten Kurs für deine Kampfsportreise.',
    'classes.mma.title': 'MMA Kurse',
    'classes.mma.description': 'Komplettes Mixed Martial Arts Training mit Schlag-, Grappling- und Bodenkampftechniken. Perfekt für alle, die vielseitige Kampffähigkeiten entwickeln möchten.',
    'classes.mma.features': ['Schlagtechniken', 'Grappling-Grundlagen', 'Bodenkampf', 'Konditionierung', 'Sparring-Sessions'],
    'classes.bjj.title': 'Brazilian Jiu-Jitsu',
    'classes.bjj.description': 'Meistere die sanfte Kunst des BJJ mit unserem umfassenden Bodenkampfprogramm. Lerne Hebelwirkung, Technik und Strategie über rohe Kraft.',
    'classes.bjj.features': ['Guard-Techniken', 'Submissions', 'Befreiungen', 'Positionskontrolle', 'Wettkampfvorbereitung'],
    'classes.grappling.title': 'Grappling',
    'classes.grappling.description': 'Entwickle deine Wrestling- und Submission-Fähigkeiten in unseren intensiven Grappling-Sessions. Fokus auf Takedowns, Kontrolle und Submissions.',
    'classes.grappling.features': ['Takedown-Techniken', 'Wrestling-Grundlagen', 'Submission Grappling', 'No-Gi Training', 'Wettkampfvorbereitung'],
    'classes.kidsBjj.title': 'BJJ für Kinder',
    'classes.kidsBjj.description': 'Sichere und spaßige Brazilian Jiu-Jitsu Kurse speziell für junge Athleten entwickelt. Aufbau von Selbstvertrauen, Disziplin und Respekt.',
    'classes.kidsBjj.features': ['Altersgerechte Techniken', 'Charakterentwicklung', 'Anti-Mobbing-Fähigkeiten', 'Körperliche Fitness', 'Spaßige Spiele und Übungen'],
    'classes.kidsGrappling.title': 'Grappling für Kinder',
    'classes.kidsGrappling.description': 'Baue Selbstvertrauen, Disziplin und körperliche Fitness durch Jugend-Grappling-Programme auf. Schwerpunkt auf Sicherheit und Fähigkeitsentwicklung.',
    'classes.kidsGrappling.features': ['Grundlegende Wrestling-Bewegungen', 'Koordinationsübungen', 'Kraftaufbau', 'Teamwork-Fähigkeiten', 'Sichere Trainingsumgebung'],
    'classes.wrestling.title': 'Wrestling',
    'classes.wrestling.description': 'Traditionelle Wrestling-Techniken und Konditionierung für Wettkampfathleten. Baue Kraft, Ausdauer und technische Kompetenz auf.',
    'classes.wrestling.features': ['Olympisches Wrestling', 'Freestyle-Techniken', 'Griechisch-römischer Stil', 'Konditionierungsprogramme', 'Wettkampftraining'],
    'classes.whatYouLearn': 'Was du lernen wirst:',
    'classes.cta.title': 'BEREIT ZUM TRAINIEREN?',
    'classes.cta.description': 'Tritt heute der Sport Academy bei und beginne deine Kampfsportreise mit Expertenunterricht und einer unterstützenden Gemeinschaft.',

    // Schedule Page
    'schedule.hero.title': 'WOCHENSTUNDENPLAN',
    'schedule.hero.description': 'Aktueller Trainingsplan - Finde die perfekte Kurszeit, die zu deinem Lebensstil passt. Alle Kurse sind für verschiedene Leistungsstufen und Altersgruppen konzipiert.',
    'schedule.campoTures': 'Standort Sand in Taufers',
    'schedule.brunico': 'Standort Bruneck',
    'schedule.tuesday': 'Dienstag',
    'schedule.thursday': 'Donnerstag',
    'schedule.monday': 'Montag',
    'schedule.wednesday': 'Mittwoch',
    'schedule.friday': 'Freitag',
    'schedule.grappling': 'Grappling',
    'schedule.mma': 'MMA',
    'schedule.bjj': 'BJJ',
    'schedule.wrestling': 'Wrestling',
    'schedule.striking': 'Schlagtechniken',
    'schedule.openMat': 'Freies Training',
    'schedule.importantInfo': 'Wichtige Informationen',
    'schedule.classGuidelines': 'Kursrichtlinien',
    'schedule.membershipBenefits': 'Mitgliedschaftsvorteile',
    'schedule.guidelines.arrive': '10 Minuten früher zum Aufwärmen kommen',
    'schedule.guidelines.water': 'Wasserflasche und Handtuch mitbringen',
    'schedule.guidelines.gi': 'Gi erforderlich für BJJ-Kurse',
    'schedule.guidelines.noGi': 'No-Gi Kleidung für MMA, Grappling und Schlagtechniken',
    'schedule.benefits.allClasses': 'Zugang zu allen geplanten Kursen',
    'schedule.benefits.openMat': 'Freie Trainingseinheiten inklusive',
    'schedule.benefits.bothLocations': 'Beide Standorte verfügbar',
    'schedule.benefits.personalTraining': 'Personaltraining verfügbar',
    'schedule.cta.title': 'PLATZ RESERVIEREN',
    'schedule.cta.description': 'Kurse füllen sich schnell. Sichere dir heute deine Mitgliedschaft und beginne das Training mit den Besten in Südtirol.',

    // Coaches Page
    'coaches.hero.title': 'UNSERE TRAINER',
    'coaches.hero.description': 'Lerne von erfahrenen Profis, die leidenschaftlich für Kampfsport sind und sich dafür einsetzen, dir beim Erreichen deiner Ziele zu helfen. Unser Trainerteam bringt jahrelange Wettkampferfahrung und bewährte Lehrmethoden mit.',
    'coaches.matteo.name': 'Matteo Parolin',
    'coaches.matteo.title': 'Cheftrainer & Gründer',
    'coaches.matteo.background': 'Matteo gründete die Sport Academy 2017 mit der Vision, erstklassiges Kampfsporttraining nach Südtirol zu bringen. Mit über 15 Jahren Erfahrung in MMA und Brazilian Jiu-Jitsu hat er auf nationaler und internationaler Ebene gekämpft.',
    'coaches.matteo.specializations': ['Mixed Martial Arts (MMA)', 'Brazilian Jiu-Jitsu (Brauner Gürtel)', 'Wettkampfvorbereitung', 'Jugendentwicklungsprogramme'],
    'coaches.matteo.achievements': ['Regionaler MMA-Champion (2019)', 'BJJ Europameisterschafts-Medaillengewinner', 'Zertifizierter Jugend-Kampfsport-Instruktor'],
    'coaches.christian.name': 'Christian Zecchetto',
    'coaches.christian.title': 'Grappling & Wrestling Trainer',
    'coaches.christian.background': 'Christian bringt eine Fülle von Wrestling- und Grappling-Expertise zur Sport Academy. Sein technischer Ansatz und seine Aufmerksamkeit für Details haben unzähligen Schülern geholfen, ihr Bodenkampfspiel und ihre Wettkampfleistung zu verbessern.',
    'coaches.christian.specializations': ['Wrestling (Freistil & Griechisch-römisch)', 'Submission Grappling', 'Takedown-Techniken', 'Kraft & Konditionierung'],
    'coaches.christian.achievements': ['Nationaler Wrestling-Meisterschafts-Finalist', 'ADCC European Trials Teilnehmer', 'Zertifizierter Wrestling-Trainer (Level 2)'],
    'coaches.background': 'Hintergrund',
    'coaches.specializations': 'Spezialisierungen',
    'coaches.achievements': 'Erfolge',
    'coaches.philosophy.title': 'UNSERE TRAININGSPHILOSOPHIE',
    'coaches.philosophy.technical.title': 'Technische Exzellenz',
    'coaches.philosophy.technical.description': 'Wir konzentrieren uns auf richtige Technik und Grundlagen und stellen sicher, dass jeder Schüler ein solides Fundament für langfristigen Erfolg aufbaut.',
    'coaches.philosophy.individual.title': 'Individuelles Wachstum',
    'coaches.philosophy.individual.description': 'Jeder Schüler ist einzigartig. Wir passen unseren Unterricht an individuelle Ziele an, ob Freizeit oder Wettkampf.',
    'coaches.philosophy.respect.title': 'Respekt & Disziplin',
    'coaches.philosophy.respect.description': 'Kampfsport lehrt mehr als Kampftechniken. Wir betonen Respekt, Disziplin und Charakterentwicklung.',
    'coaches.cta.title': 'TRAINIERE MIT DEN BESTEN',
    'coaches.cta.description': 'Erlebe erstklassigen Unterricht und persönliche Betreuung. Beginne deine Reise mit dem Expertentrainerteam der Sport Academy.',

    // Membership Page
    'membership.hero.title': 'MITGLIEDSCHAFTSPLÄNE',
    'membership.hero.description': 'Wähle den Mitgliedschaftsplan, der zu deinen Trainingszielen und deinem Zeitplan passt. Alle Mitgliedschaften beinhalten Zugang zu beiden Standorten und allen geplanten Kursen. Keine versteckten Gebühren, keine langfristigen Verträge.',
    'membership.mainSeason.title': 'Hauptsaison',
    'membership.mainSeason.period': 'September - Juni',
    'membership.mainSeason.duration': '10 Monate intensives Training',
    'membership.mainSeason.mostPopular': 'AM BELIEBTESTEN',
    'membership.summerSeason.title': 'Sommersaison',
    'membership.summerSeason.period': 'Juni - September',
    'membership.summerSeason.duration': '3 Monate Sommertraining',
    'membership.bjjOnly.title': 'NUR JIU JITSU MITGLIEDSCHAFT',
    'membership.bjjOnly.subtitle': 'Spezielles Brazilian Jiu-Jitsu Training für die Sommersaison',
    'membership.bjjOnly.program': 'BJJ Sommerprogramm',
    'membership.bjjOnly.description': '3 Monate fokussiertes BJJ-Training',
    'membership.adults': 'Erwachsene',
    'membership.students': 'Studenten',
    'membership.month': 'Monat',
    'membership.whatsIncluded': 'Was ist enthalten:',
    'membership.mainIncludes': ['Unbegrenzter Zugang zu allen Kursen', 'Beide Standorte Sand in Taufers & Bruneck', 'Freie Trainingseinheiten', 'Wettkampfvorbereitung', 'Personaltraining-Rabatte'],
    'membership.summerIncludes': ['Zugang zu Sommerstundenplan-Kursen', 'Beide Standorte verfügbar', 'Offene Trainingseinheiten', 'Flexibler Sommerstundenplan', 'Outdoor-Trainingsmöglichkeiten'],
    'membership.bjjIncludes': ['Zugang nur zu allen BJJ-Kursen', 'Beide Standorte Sand in Taufers & Bruneck', 'Gi und No-Gi Training', 'Fokus auf Technikverfeinerung', 'BJJ-spezifische freie Trainingseinheiten'],
    'membership.selectMainSeason': 'HAUPTSAISON WÄHLEN',
    'membership.selectSummerSeason': 'SOMMERSAISON WÄHLEN',
    'membership.selectBjjOnly': 'NUR BJJ WÄHLEN',
    'membership.additionalServices.title': 'ZUSÄTZLICHE DIENSTLEISTUNGEN',
    'membership.additionalServices.description': 'Verbessere dein Training mit unseren spezialisierten Dienstleistungen und Programmen',
    'membership.personalTraining.title': 'Personaltraining',
    'membership.personalTraining.description': 'Einzelcoaching-Sessions auf deine spezifischen Ziele zugeschnitten',
    'membership.personalTraining.price': '€50/Session',
    'membership.personalTraining.duration': '60 Minuten',
    'membership.competitionPrep.title': 'Wettkampfvorbereitung',
    'membership.competitionPrep.description': 'Spezialisiertes Training für bevorstehende Turniere und Wettkämpfe',
    'membership.competitionPrep.price': '€80/Session',
    'membership.competitionPrep.duration': '90 Minuten',
    'membership.seminars.title': 'Seminare & Workshops',
    'membership.seminars.description': 'Spezielle Veranstaltungen mit Gastinstruktoren und fortgeschrittenen Techniken',
    'membership.seminars.price': '€30/Veranstaltung',
    'membership.seminars.duration': '3-4 Stunden',
    'membership.faq.title': 'HÄUFIG GESTELLTE FRAGEN',
    'membership.faq.seasons.question': 'Was ist der Unterschied zwischen den Saisons?',
    'membership.faq.seasons.answer': 'Die Hauptsaison (September-Juni) bietet unser vollständiges Programm mit regulären Kursen und Wettkampfvorbereitung. Die Sommersaison (Juni-September) hat einen entspannteren Zeitplan, perfekt um während der Urlaubsmonate fit zu bleiben.',
    'membership.faq.locations.question': 'Kann ich an beiden Standorten trainieren?',
    'membership.faq.locations.answer': 'Ja! Alle Mitgliedschaften beinhalten Zugang zu beiden unserer Einrichtungen in Sand in Taufers und Bruneck. Du kannst je nach deinem Zeitplan Kurse an beiden Standorten besuchen.',
    'membership.faq.trial.question': 'Bietet ihr Probestunden an?',
    'membership.faq.trial.answer': 'Absolut! Wir bieten eine kostenlose Probestunde für neue Schüler an. Kontaktiere uns, um deine Probestunde zu vereinbaren und unser Training aus erster Hand zu erleben.',
    'membership.faq.equipment.question': 'Welche Ausrüstung brauche ich?',
    'membership.faq.equipment.answer': 'Für BJJ-Kurse brauchst du einen Gi (Uniform). Für MMA und Grappling ist bequeme Sportkleidung ausreichend. Wir empfehlen, eine Wasserflasche und ein Handtuch zu allen Kursen mitzubringen.',
    'membership.cta.title': 'BEGINNE DEINE REISE HEUTE',
    'membership.cta.description': 'Tritt der Sport Academy bei und werde Teil von Südtirols führender Kampfsportgemeinschaft. Deine Transformation beginnt hier.',

    // Contact Page
    'contact.hero.title': 'KONTAKT & BESUCH',
    'contact.hero.description': 'Nimm Kontakt mit der Sport Academy auf und besuche unsere erstklassigen Trainingseinrichtungen. Wir sind hier, um dir beim Start deiner Kampfsportreise mit Expertenberatung und Unterstützung zu helfen.',
    'contact.getInTouch.title': 'KONTAKT AUFNEHMEN',
    'contact.getInTouch.subtitle': 'Mehrere Wege, um mit unserem Team in Kontakt zu treten',
    'contact.callUs': 'Anrufen',
    'contact.instagram': 'Instagram',
    'contact.locations.title': 'UNSERE STANDORTE',
    'contact.locations.subtitle': 'Zwei praktische Einrichtungen in Südtirol',
    'contact.campoTures': 'Sand in Taufers',
    'contact.brunico': 'Bruneck',
    'contact.address': 'Adresse',
    'contact.trainingSchedule': 'Trainingsplan',
    'contact.landmarkDirections': 'Wegbeschreibung zu Orientierungspunkten',
    'contact.availableClasses': 'Verfügbare Kurse',
    'contact.campoTures.address': 'Hugo von Taufers Straße 8\nSand in Taufers, Südtirol\nItalien',
    'contact.brunico.address': 'Teresa Riedl Straße 3\n39031 Bruneck BZ\nSüdtirol, Italien',
    'contact.campoTures.directions': 'Im Stadtzentrum gelegen, 50m von der Hauptkirche entfernt. Suche nach dem Sport Academy Schild neben der Apotheke.',
    'contact.brunico.directions': '5 Minuten zu Fuß vom Bahnhof Bruneck. In der Nähe des Sportkomplexes, gegenüber dem öffentlichen Schwimmbad.',
    'contact.campoTures.classes': ['MMA Kurse', 'Brazilian Jiu-Jitsu', 'Grappling', 'Kinder BJJ'],
    'contact.brunico.classes': ['Brazilian Jiu-Jitsu', 'Wrestling', 'Kinder Grappling', 'Freies Training'],
    'contact.parking.title': 'PARKEN & BARRIEREFREIHEIT',
    'contact.parking.subtitle': 'Einfacher Zugang und bequemes Parken an beiden Standorten',
    'contact.parking': 'Parken',
    'contact.publicTransport': 'Öffentliche Verkehrsmittel',
    'contact.accessibility': 'Barrierefreiheit',
    'contact.campoTures.parking': 'Kostenlose Straßenparkplätze in der Hugo von Taufers Straße und umliegenden Straßen verfügbar. Öffentlicher Parkplatz 100m entfernt (€1/Stunde während Geschäftszeiten, abends kostenlos).',
    'contact.campoTures.transport': 'Regelmäßiger Busservice von Bruneck (Linie 441). Bushaltestelle "Sand in Taufers Zentrum" ist 2 Minuten zu Fuß vom Fitnessstudio entfernt.',
    'contact.campoTures.accessibility': 'Erdgeschosszugang mit breitem Eingang. Barrierefreie Toiletten verfügbar.',
    'contact.brunico.parking': 'Kostenlose Parkplätze in der Teresa Riedl Straße verfügbar. Großer öffentlicher Parkplatz in der Nähe des Sportkomplexes (kostenlos nach 18:00 und am Wochenende).',
    'contact.brunico.transport': '5 Minuten zu Fuß vom Bahnhof Bruneck. Ausgezeichnete Verbindungen nach Bozen, Innsbruck und größeren Städten. Buslinien 441, 442 und 445.',
    'contact.brunico.accessibility': 'Rollstuhlgerechter Eingang und Einrichtungen. Aufzugszugang zu allen Etagen.',
    'contact.visitRequirements.title': 'BESUCHSANFORDERUNGEN',
    'contact.visitRequirements.subtitle': 'Was du vor deinem ersten Besuch wissen solltest',
    'contact.firstTimeVisitors': 'Erstbesucher',
    'contact.whatToBring': 'Was mitbringen',
    'contact.whatWeProvide': 'Was wir bereitstellen',
    'contact.specialInstructions': 'Besondere Anweisungen',
    'contact.bring': ['Gültiger Ausweis für Anmeldung', 'Bequeme Sportkleidung', 'Wasserflasche und Handtuch', 'Positive Einstellung und offenen Geist'],
    'contact.provide': ['Kostenlose Probestunde (erster Besuch)', 'Grundlegende Handschuhe & Schienbeinschoner für MMA-Kurse (vorübergehend)', 'Einrichtungsführung und Orientierung', 'Persönliche Beratung mit Trainern'],
    'contact.instructions.age': 'Altersanforderungen: 16+ für Erwachsenenkurse, 6-15 für Kinderprogramme',
    'contact.instructions.health': 'Gesundheit: Bitte informiere uns über Verletzungen oder medizinische Beschwerden',
    'contact.instructions.equipment': 'Ausrüstung: Grundlegende Handschuhe & Schienbeinschoner vorübergehend bereitgestellt - Schüler sollten ihre eigene Ausrüstung kaufen',
    'contact.instructions.payment': 'Zahlung: Bar und Karte akzeptiert',
    'contact.cta.title': 'BEREIT ZU BEGINNEN?',
    'contact.cta.description': 'Mache den ersten Schritt zu deiner Kampfsportreise. Kontaktiere uns heute und entdecke dein Potenzial.',

    // Footer
    'footer.tagline': 'Elite MMA, BJJ & Grappling Training in Südtirol',
    'footer.subtitle': 'Kämpfer schmieden seit 2017',
    'footer.copyright': '© 2025 Sport Academy. Alle Rechte vorbehalten.',
  },

  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.classes': 'Corsi',
    'nav.schedule': 'Orari',
    'nav.coaches': 'Istruttori',
    'nav.membership': 'Abbonamenti',
    'nav.contact': 'Contatti',

    // Common
    'common.joinNow': 'ISCRIVITI ORA',
    'common.viewClasses': 'VEDI CORSI',
    'common.learnMore': 'Scopri di più',
    'common.backToClasses': 'TORNA AI CORSI',
    'common.contactUs': 'CONTATTACI',
    'common.callNow': 'CHIAMA ORA',
    'common.viewSchedule': 'VEDI ORARI',
    'common.viewMembership': 'VEDI ABBONAMENTI',
    'common.joinSportAcademy': 'UNISCITI A SPORT ACADEMY',
    'common.allLevels': 'Tutti i livelli',
    'common.ages': 'Età',
    'common.registerOnline': 'REGISTRATI ONLINE',
    'common.bookClasses': 'Prenota corsi',
    'common.visitUs': 'Visitaci',
    'common.dropInWelcome': 'Visite spontanee benvenute',
    'common.duringTrainingHours': 'Durante gli orari di allenamento',
    'common.instantConfirmation': 'Conferma immediata',
    'common.responseWithin2Hours': 'Risposta entro 2 ore',
    'common.dailyUpdatesAndDMs': 'Aggiornamenti quotidiani e DM',

    // Home Page
    'home.hero.title': 'SPORT ACADEMY',
    'home.hero.subtitle': 'Forgiamo combattenti dal 2017',
    'home.welcome.title': 'BENVENUTI A SPORT ACADEMY',
    'home.welcome.description': 'Dal 2017, Sport Academy è la destinazione principale per l\'allenamento di arti marziali in Alto Adige. Offriamo istruzione di livello mondiale in MMA, Brazilian Jiu-Jitsu e Grappling nelle nostre due strutture all\'avanguardia.',
    'home.stats.yearsOfExcellence': 'Anni di Eccellenza',
    'home.stats.yearsDescription': 'Fondata nel 2017, sviluppiamo combattenti da oltre 8 anni',
    'home.stats.trainingLocations': 'Sedi di Allenamento',
    'home.stats.locationsDescription': 'Strutture convenienti a Campo Tures e Brunico',
    'home.stats.trainingPrograms': 'Programmi di Allenamento',
    'home.stats.programsDescription': 'Corsi completi per adulti e bambini di tutti i livelli',
    'home.stats.exploreClasses': 'ESPLORA I NOSTRI CORSI',
    'home.trainLikeFighter.title': 'ALLENATI COME UN COMBATTENTE',
    'home.trainLikeFighter.subtitle': 'Padroneggia le arti del combattimento con istruzione professionale',
    'home.mma.description': 'Allenamento completo di arti marziali miste che combina tecniche di striking, grappling e combattimento a terra.',
    'home.bjj.description': 'Padroneggia l\'arte gentile del Brazilian Jiu-Jitsu con tecniche complete di combattimento a terra.',
    'home.grappling.description': 'Sviluppa abilità di wrestling e submission attraverso allenamento intensivo di grappling no-gi.',
    'home.getStarted.title': 'INIZIA OGGI',
    'home.getStarted.subtitle': 'Tutto ciò di cui hai bisogno per iniziare il tuo viaggio nelle arti marziali',
    'home.quickLinks.viewClasses': 'Vedi Corsi',
    'home.quickLinks.viewClassesDesc': 'Esplora i nostri programmi di allenamento',
    'home.quickLinks.checkSchedule': 'Controlla Orari',
    'home.quickLinks.checkScheduleDesc': 'Trova l\'orario perfetto per il corso',
    'home.quickLinks.membershipPlans': 'Piani di Abbonamento',
    'home.quickLinks.membershipPlansDesc': 'Scegli il tuo pacchetto di allenamento',
    'home.quickLinks.contactUs': 'Contattaci',
    'home.quickLinks.contactUsDesc': 'Mettiti in contatto con il nostro team',

    // Classes Page
    'classes.hero.title': 'I NOSTRI CORSI',
    'classes.hero.description': 'Programmi di allenamento professionali progettati per tutti i livelli di abilità. Dai principianti che muovono i primi passi agli atleti avanzati che si preparano per le competizioni, abbiamo il corso perfetto per il tuo viaggio nelle arti marziali.',
    'classes.mma.title': 'Corsi MMA',
    'classes.mma.description': 'Allenamento completo di arti marziali miste che combina tecniche di striking, grappling e combattimento a terra. Perfetto per chi vuole sviluppare abilità di combattimento complete.',
    'classes.mma.features': ['Tecniche di striking', 'Fondamenti di grappling', 'Combattimento a terra', 'Condizionamento', 'Sessioni di sparring'],
    'classes.bjj.title': 'Brazilian Jiu-Jitsu',
    'classes.bjj.description': 'Padroneggia l\'arte gentile del BJJ con il nostro programma completo di combattimento a terra. Impara leva, tecnica e strategia sulla forza bruta.',
    'classes.bjj.features': ['Tecniche di guardia', 'Sottomissioni', 'Fughe', 'Controllo posizionale', 'Preparazione competitiva'],
    'classes.grappling.title': 'Grappling',
    'classes.grappling.description': 'Sviluppa le tue abilità di wrestling e submission nelle nostre sessioni intensive di grappling. Focus su takedown, controllo e sottomissioni.',
    'classes.grappling.features': ['Tecniche di takedown', 'Fondamenti di wrestling', 'Submission grappling', 'Allenamento no-gi', 'Preparazione competitiva'],
    'classes.kidsBjj.title': 'BJJ per Bambini',
    'classes.kidsBjj.description': 'Corsi di Brazilian Jiu-Jitsu sicuri e divertenti progettati specificamente per giovani atleti. Costruzione di fiducia, disciplina e rispetto.',
    'classes.kidsBjj.features': ['Tecniche appropriate per l\'età', 'Sviluppo del carattere', 'Abilità anti-bullismo', 'Fitness fisico', 'Giochi e esercizi divertenti'],
    'classes.kidsGrappling.title': 'Grappling per Bambini',
    'classes.kidsGrappling.description': 'Costruisci fiducia, disciplina e fitness fisico attraverso programmi di grappling giovanile. Enfasi su sicurezza e sviluppo delle abilità.',
    'classes.kidsGrappling.features': ['Movimenti base di wrestling', 'Esercizi di coordinazione', 'Costruzione della forza', 'Abilità di squadra', 'Ambiente di allenamento sicuro'],
    'classes.wrestling.title': 'Wrestling',
    'classes.wrestling.description': 'Tecniche di wrestling tradizionali e condizionamento per atleti competitivi. Costruisci forza, resistenza e competenza tecnica.',
    'classes.wrestling.features': ['Wrestling olimpico', 'Tecniche freestyle', 'Stile greco-romano', 'Programmi di condizionamento', 'Allenamento competitivo'],
    'classes.whatYouLearn': 'Cosa imparerai:',
    'classes.cta.title': 'PRONTO PER INIZIARE AD ALLENARTI?',
    'classes.cta.description': 'Unisciti a Sport Academy oggi e inizia il tuo viaggio nelle arti marziali con istruzione esperta e una comunità di supporto.',

    // Schedule Page
    'schedule.hero.title': 'ORARIO SETTIMANALE',
    'schedule.hero.description': 'Orario di Allenamento Attuale - Trova l\'orario perfetto del corso che si adatta al tuo stile di vita. Tutti i corsi sono progettati per accogliere diversi livelli di abilità e gruppi di età.',
    'schedule.campoTures': 'Sede Campo Tures',
    'schedule.brunico': 'Sede Brunico',
    'schedule.tuesday': 'Martedì',
    'schedule.thursday': 'Giovedì',
    'schedule.monday': 'Lunedì',
    'schedule.wednesday': 'Mercoledì',
    'schedule.friday': 'Venerdì',
    'schedule.grappling': 'Grappling',
    'schedule.mma': 'MMA',
    'schedule.bjj': 'BJJ',
    'schedule.wrestling': 'Wrestling',
    'schedule.striking': 'Striking',
    'schedule.openMat': 'Allenamento Libero',
    'schedule.importantInfo': 'Informazioni Importanti',
    'schedule.classGuidelines': 'Linee Guida del Corso',
    'schedule.membershipBenefits': 'Benefici dell\'Abbonamento',
    'schedule.guidelines.arrive': 'Arriva 10 minuti prima per il riscaldamento',
    'schedule.guidelines.water': 'Porta bottiglia d\'acqua e asciugamano',
    'schedule.guidelines.gi': 'Gi richiesto per i corsi BJJ',
    'schedule.guidelines.noGi': 'Abbigliamento no-gi per MMA, Grappling e Striking',
    'schedule.benefits.allClasses': 'Accesso a tutti i corsi programmati',
    'schedule.benefits.openMat': 'Sessioni di allenamento libero incluse',
    'schedule.benefits.bothLocations': 'Entrambe le sedi disponibili',
    'schedule.benefits.personalTraining': 'Allenamento personale disponibile',
    'schedule.cta.title': 'PRENOTA IL TUO POSTO',
    'schedule.cta.description': 'I corsi si riempiono velocemente. Assicurati il tuo abbonamento oggi e inizia ad allenarti con i migliori in Alto Adige.',

    // Coaches Page
    'coaches.hero.title': 'I NOSTRI ISTRUTTORI',
    'coaches.hero.description': 'Impara da professionisti esperti che sono appassionati di arti marziali e dedicati ad aiutarti a raggiungere i tuoi obiettivi. Il nostro team di istruttori porta anni di esperienza competitiva e metodi di insegnamento comprovati.',
    'coaches.matteo.name': 'Matteo Parolin',
    'coaches.matteo.title': 'Capo Istruttore & Fondatore',
    'coaches.matteo.background': 'Matteo ha fondato Sport Academy nel 2017 con la visione di portare allenamento di arti marziali di livello mondiale in Alto Adige. Con oltre 15 anni di esperienza in MMA e Brazilian Jiu-Jitsu, ha gareggiato a livello nazionale e internazionale.',
    'coaches.matteo.specializations': ['Arti Marziali Miste (MMA)', 'Brazilian Jiu-Jitsu (Cintura Marrone)', 'Preparazione Competitiva', 'Programmi di Sviluppo Giovanile'],
    'coaches.matteo.achievements': ['Campione Regionale MMA (2019)', 'Medagliato Campionato Europeo BJJ', 'Istruttore Certificato Arti Marziali Giovanili'],
    'coaches.christian.name': 'Christian Zecchetto',
    'coaches.christian.title': 'Istruttore Grappling & Wrestling',
    'coaches.christian.background': 'Christian porta una ricchezza di esperienza in wrestling e grappling a Sport Academy. Il suo approccio tecnico e l\'attenzione ai dettagli hanno aiutato innumerevoli studenti a migliorare il loro gioco a terra e le prestazioni competitive.',
    'coaches.christian.specializations': ['Wrestling (Stile Libero & Greco-Romano)', 'Submission Grappling', 'Tecniche di Takedown', 'Forza & Condizionamento'],
    'coaches.christian.achievements': ['Finalista Campionato Nazionale Wrestling', 'Competitore ADCC European Trials', 'Istruttore Wrestling Certificato (Livello 2)'],
    'coaches.background': 'Background',
    'coaches.specializations': 'Specializzazioni',
    'coaches.achievements': 'Risultati',
    'coaches.philosophy.title': 'LA NOSTRA FILOSOFIA DI INSEGNAMENTO',
    'coaches.philosophy.technical.title': 'Eccellenza Tecnica',
    'coaches.philosophy.technical.description': 'Ci concentriamo sulla tecnica corretta e sui fondamenti, assicurando che ogni studente costruisca una base solida per il successo a lungo termine.',
    'coaches.philosophy.individual.title': 'Crescita Individuale',
    'coaches.philosophy.individual.description': 'Ogni studente è unico. Adattiamo la nostra istruzione per soddisfare gli obiettivi individuali, che siano ricreativi o competitivi.',
    'coaches.philosophy.respect.title': 'Rispetto & Disciplina',
    'coaches.philosophy.respect.description': 'Le arti marziali insegnano più delle tecniche di combattimento. Enfatizziamo rispetto, disciplina e sviluppo del carattere.',
    'coaches.cta.title': 'ALLENATI CON I MIGLIORI',
    'coaches.cta.description': 'Sperimenta istruzione di livello mondiale e attenzione personalizzata. Inizia il tuo viaggio con il team di istruttori esperti di Sport Academy.',

    // Membership Page
    'membership.hero.title': 'PIANI DI ABBONAMENTO',
    'membership.hero.description': 'Scegli il piano di abbonamento che si adatta ai tuoi obiettivi di allenamento e al tuo programma. Tutti gli abbonamenti includono accesso a entrambe le sedi e a tutti i corsi programmati. Nessuna tariffa nascosta, nessun contratto a lungo termine.',
    'membership.mainSeason.title': 'Stagione Principale',
    'membership.mainSeason.period': 'Settembre - Giugno',
    'membership.mainSeason.duration': '10 mesi di allenamento intensivo',
    'membership.mainSeason.mostPopular': 'PIÙ POPOLARE',
    'membership.summerSeason.title': 'Stagione Estiva',
    'membership.summerSeason.period': 'Giugno - Settembre',
    'membership.summerSeason.duration': '3 mesi di allenamento estivo',
    'membership.bjjOnly.title': 'ABBONAMENTO SOLO JIU JITSU',
    'membership.bjjOnly.subtitle': 'Allenamento dedicato di Brazilian Jiu-Jitsu per la stagione estiva',
    'membership.bjjOnly.program': 'Programma BJJ Estivo',
    'membership.bjjOnly.description': '3 mesi di allenamento BJJ focalizzato',
    'membership.adults': 'Adulti',
    'membership.students': 'Studenti',
    'membership.month': 'mese',
    'membership.whatsIncluded': 'Cosa è incluso:',
    'membership.mainIncludes': ['Accesso illimitato a tutti i corsi', 'Entrambe le sedi Campo Tures & Brunico', 'Sessioni di allenamento libero', 'Preparazione competitiva', 'Sconti allenamento personale'],
    'membership.summerIncludes': ['Accesso ai corsi dell\'orario estivo', 'Entrambe le sedi disponibili', 'Sessioni di allenamento aperto', 'Orario estivo flessibile', 'Opportunità di allenamento all\'aperto'],
    'membership.bjjIncludes': ['Accesso solo a tutti i corsi BJJ', 'Entrambe le sedi Campo Tures & Brunico', 'Allenamento Gi e No-Gi', 'Focus sul perfezionamento tecnico', 'Sessioni di allenamento libero specifiche per BJJ'],
    'membership.selectMainSeason': 'SELEZIONA STAGIONE PRINCIPALE',
    'membership.selectSummerSeason': 'SELEZIONA STAGIONE ESTIVA',
    'membership.selectBjjOnly': 'SELEZIONA SOLO BJJ',
    'membership.additionalServices.title': 'SERVIZI AGGIUNTIVI',
    'membership.additionalServices.description': 'Migliora il tuo allenamento con i nostri servizi e programmi specializzati',
    'membership.personalTraining.title': 'Allenamento Personale',
    'membership.personalTraining.description': 'Sessioni di coaching uno-a-uno su misura per i tuoi obiettivi specifici',
    'membership.personalTraining.price': '€50/sessione',
    'membership.personalTraining.duration': '60 minuti',
    'membership.competitionPrep.title': 'Preparazione Competitiva',
    'membership.competitionPrep.description': 'Allenamento specializzato per tornei e competizioni imminenti',
    'membership.competitionPrep.price': '€80/sessione',
    'membership.competitionPrep.duration': '90 minuti',
    'membership.seminars.title': 'Seminari & Workshop',
    'membership.seminars.description': 'Eventi speciali con istruttori ospiti e tecniche avanzate',
    'membership.seminars.price': '€30/evento',
    'membership.seminars.duration': '3-4 ore',
    'membership.faq.title': 'DOMANDE FREQUENTI',
    'membership.faq.seasons.question': 'Qual è la differenza tra le stagioni?',
    'membership.faq.seasons.answer': 'La Stagione Principale (Settembre-Giugno) offre il nostro programma completo con corsi regolari e preparazione competitiva. La Stagione Estiva (Giugno-Settembre) ha un programma più rilassato perfetto per mantenere la forma durante i mesi di vacanza.',
    'membership.faq.locations.question': 'Posso allenarmi in entrambe le sedi?',
    'membership.faq.locations.answer': 'Sì! Tutti gli abbonamenti includono accesso a entrambe le nostre strutture di Campo Tures e Brunico. Puoi partecipare ai corsi in entrambe le sedi in base al tuo programma.',
    'membership.faq.trial.question': 'Offrite lezioni di prova?',
    'membership.faq.trial.answer': 'Assolutamente! Offriamo una lezione di prova gratuita per i nuovi studenti. Contattaci per programmare la tua prova e sperimentare il nostro allenamento in prima persona.',
    'membership.faq.equipment.question': 'Di quale attrezzatura ho bisogno?',
    'membership.faq.equipment.answer': 'Per i corsi BJJ, avrai bisogno di un gi (uniforme). Per MMA e grappling, abbigliamento sportivo comodo è sufficiente. Raccomandiamo di portare una bottiglia d\'acqua e un asciugamano a tutti i corsi.',
    'membership.cta.title': 'INIZIA IL TUO VIAGGIO OGGI',
    'membership.cta.description': 'Unisciti a Sport Academy e diventa parte della comunità di arti marziali premier dell\'Alto Adige. La tua trasformazione inizia qui.',

    // Contact Page
    'contact.hero.title': 'CONTATTI & VISITE',
    'contact.hero.description': 'Mettiti in contatto con Sport Academy e visita le nostre strutture di allenamento di livello mondiale. Siamo qui per aiutarti a iniziare il tuo viaggio nelle arti marziali con guida esperta e supporto.',
    'contact.getInTouch.title': 'METTITI IN CONTATTO',
    'contact.getInTouch.subtitle': 'Diversi modi per connettersi con il nostro team',
    'contact.callUs': 'Chiamaci',
    'contact.instagram': 'Instagram',
    'contact.locations.title': 'LE NOSTRE SEDI',
    'contact.locations.subtitle': 'Due strutture convenienti in Alto Adige',
    'contact.campoTures': 'Campo Tures',
    'contact.brunico': 'Brunico',
    'contact.address': 'Indirizzo',
    'contact.trainingSchedule': 'Orario di Allenamento',
    'contact.landmarkDirections': 'Indicazioni per Punti di Riferimento',
    'contact.availableClasses': 'Corsi Disponibili',
    'contact.campoTures.address': 'Via Hugo von Taufers 8\nCampo Tures, Alto Adige\nItalia',
    'contact.brunico.address': 'Via Teresa Riedl 3\n39031 Brunico BZ\nAlto Adige, Italia',
    'contact.campoTures.directions': 'Situato nel centro del paese, a 50m dalla chiesa principale. Cerca l\'insegna Sport Academy accanto alla farmacia.',
    'contact.brunico.directions': '5 minuti a piedi dalla stazione ferroviaria di Brunico. Vicino al complesso sportivo, di fronte alla piscina pubblica.',
    'contact.campoTures.classes': ['Corsi MMA', 'Brazilian Jiu-Jitsu', 'Grappling', 'BJJ Bambini'],
    'contact.brunico.classes': ['Brazilian Jiu-Jitsu', 'Wrestling', 'Grappling Bambini', 'Allenamento Libero'],
    'contact.parking.title': 'PARCHEGGIO & ACCESSIBILITÀ',
    'contact.parking.subtitle': 'Accesso facile e parcheggio conveniente in entrambe le sedi',
    'contact.parking': 'Parcheggio',
    'contact.publicTransport': 'Trasporti Pubblici',
    'contact.accessibility': 'Accessibilità',
    'contact.campoTures.parking': 'Parcheggio gratuito in strada disponibile in Via Hugo von Taufers e strade circostanti. Parcheggio pubblico a 100m di distanza (€1/ora durante orari lavorativi, gratuito la sera).',
    'contact.campoTures.transport': 'Servizio autobus regolare da Brunico (Linea 441). Fermata autobus "Campo Tures Centro" è a 2 minuti a piedi dalla palestra.',
    'contact.campoTures.accessibility': 'Accesso al piano terra con ingresso ampio. Servizi igienici accessibili disponibili.',
    'contact.brunico.parking': 'Parcheggio gratuito disponibile in Via Teresa Riedl. Grande area di parcheggio pubblico vicino al complesso sportivo (gratuito dopo le 18:00 e nei weekend).',
    'contact.brunico.transport': '5 minuti a piedi dalla stazione ferroviaria di Brunico. Eccellenti collegamenti per Bolzano, Innsbruck e città principali. Linee autobus 441, 442 e 445.',
    'contact.brunico.accessibility': 'Ingresso e strutture accessibili in sedia a rotelle. Accesso con ascensore a tutti i piani.',
    'contact.visitRequirements.title': 'REQUISITI PER LA VISITA',
    'contact.visitRequirements.subtitle': 'Cosa sapere prima della tua prima visita',
    'contact.firstTimeVisitors': 'Visitatori per la Prima Volta',
    'contact.whatToBring': 'Cosa Portare',
    'contact.whatWeProvide': 'Cosa Forniamo',
    'contact.specialInstructions': 'Istruzioni Speciali',
    'contact.bring': ['Documento d\'identità valido per registrazione', 'Abbigliamento sportivo comodo', 'Bottiglia d\'acqua e asciugamano', 'Atteggiamento positivo e mente aperta'],
    'contact.provide': ['Lezione di prova gratuita (prima visita)', 'Guanti base & parastinchi per corsi MMA (temporaneo)', 'Tour della struttura e orientamento', 'Consulenza personale con istruttori'],
    'contact.instructions.age': 'Requisiti di età: 16+ per corsi adulti, 6-15 per programmi bambini',
    'contact.instructions.health': 'Salute: Per favore informaci di eventuali infortuni o condizioni mediche',
    'contact.instructions.equipment': 'Attrezzatura: Guanti base & parastinchi forniti temporaneamente - gli studenti dovrebbero acquistare la propria attrezzatura',
    'contact.instructions.payment': 'Pagamento: Contanti e carta accettati',
    'contact.cta.title': 'PRONTO PER INIZIARE?',
    'contact.cta.description': 'Fai il primo passo verso il tuo viaggio nelle arti marziali. Contattaci oggi e scopri il tuo potenziale.',

    // Footer
    'footer.tagline': 'Allenamento Elite MMA, BJJ & Grappling in Alto Adige',
    'footer.subtitle': 'Forgiamo combattenti dal 2017',
    'footer.copyright': '© 2025 Sport Academy. Tutti i diritti riservati.',
  }
};